### ISSUE TITLE
Functions should be scoped to a namespace

### ISSUE THREAD

**Issue by shyim** [darkterminal/libsql-client-php#13]
https://github.com/darkterminal/libsql-client-php/blob/151f56d3923c45c9b7450b33ea41c19a90bff29c/src/Utils/helpers.php

All that functions should be scoped to a namespace, or maybe a Helper class with many static methods?

When my app has a `expandConfig` function it will conflict

**Comment by darkterminal** [comment]
That's nice catch btw! Noted! :notebook:

**Comment by shyim** [comment]
same with constants :)

**Comment by darkterminal** [comment]
Other constants come from the core dependency [`libsql-php-ext`](https://github.com/darkterminal/libsql-php-ext).
